apiVersion: v1
kind: Service
metadata:
  name: httpd-proxy
  labels:
    app: httpd_proxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: httpd-proxy
status:
  loadBalancer: {}
