apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - image: docker.io/pimsubc/idp-testbed_ldap
        name: ldap
      restartPolicy: Always
